In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


Downloaded a sample dataset from Kaggle

In [2]:
import pandas as pd
imdbratings1_df=pd.read_csv('gdrive/My Drive/DSFinalCapstone/Imdb_Ratings_New.csv')
imdbratings2_df=pd.read_csv('gdrive/My Drive/DSFinalCapstone/Imdb_Ratings_New2.csv')
imdbratings3_df=pd.read_csv('gdrive/My Drive/DSFinalCapstone/Imdb_Ratings_New3.csv')
imdbratings4_df=pd.read_csv('gdrive/My Drive/DSFinalCapstone/Imdb_Ratings_New4.csv')

In [3]:
frames = [imdbratings1_df, imdbratings2_df, imdbratings3_df, imdbratings4_df]
imdbratings_df = pd.concat(frames)

In [4]:
imdbratings_df.head()

New Field
0  1. The Revenant (I) (2015)\n\nR | 156 min | Ac...
1  2. The Invisible Guest (2016)\n\nTV-MA | 106 m...
2  3. Green Book (2018)\n\nPG-13 | 130 min | Biog...
3  4. Hacksaw Ridge (2016)\n\nR | 139 min | Biogr...
4  5. Molly's Game (2017)\n\nR | 140 min | Biogra...

In [5]:
# create a sample DataFrame
df1 = pd.DataFrame()

# split the Name column into two columns
df1[['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8', 'col9', 'col10', 'col11', 'col12', 'col13', 'col14', 'col15']] = imdbratings_df['New Field'].str.split('\n', expand=True)

# view the updated DataFrame
#print(df1)

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 400 entries, 0 to 99
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    400 non-null    object
 1   col2    400 non-null    object
 2   col3    400 non-null    object
 3   col4    400 non-null    object
 4   col5    400 non-null    object
 5   col6    400 non-null    object
 6   col7    400 non-null    object
 7   col8    400 non-null    object
 8   col9    400 non-null    object
 9   col10   400 non-null    object
 10  col11   400 non-null    object
 11  col12   400 non-null    object
 12  col13   15 non-null     object
 13  col14   15 non-null     object
 14  col15   15 non-null     object
dtypes: object(15)
memory usage: 50.0+ KB


In [7]:
df1.head()

col1 col2  \
0     1. The Revenant (I) (2015)        
1  2. The Invisible Guest (2016)        
2           3. Green Book (2018)        
3        4. Hacksaw Ridge (2016)        
4         5. Molly's Game (2017)        

                                         col3 col4   col5                col6  \
0      R | 156 min | Action, Adventure, Drama          8    Rate 76 Metascore   
1     TV-MA | 106 min | Crime, Drama, Mystery          8                 Rate   
2  PG-13 | 130 min | Biography, Comedy, Drama        8.2    Rate 69 Metascore   
3     R | 139 min | Biography, Drama, History        8.1    Rate 71 Metascore   
4       R | 140 min | Biography, Crime, Drama        7.4    Rate 71 Metascore   

  col7                                               col8 col9  \
0       A frontiersman on a fur trading expedition in ...        
1       A successful entrepreneur accused of murder an...        
2       A working-class Italian-American bouncer becom...        
3       World War II American Army Medic Desmond T. Do...        
4       The true story of Molly Bloom, an Olympic-clas...        

                                               col10 col11  \
0  Director: Alejandro G. Iñárritu | Stars: Leona...         
1  Director: Oriol Paulo | Stars: Mario Casas, An...         
2  Director: Peter Farrelly | Stars: Viggo Morten...         
3  Director: Mel Gibson | Stars: Andrew Garfield,...         
4  Director: Aaron Sorkin | Stars: Jessica Chasta...         

                              col12 col13          col14  \
0  Votes: 867,466 | Gross: $183.64M         Watch on Max   
1                    Votes: 191,184  None           None   
2   Votes: 560,737 | Gross: $85.08M  None           None   
3   Votes: 587,526 | Gross: $67.21M  None           None   
4   Votes: 186,071 | Gross: $28.78M  None           None   

                       col15  
0  with Prime Video Channels  
1                       None  
2                       None  
3                       None  
4                       None

In [8]:
import numpy as np
#df2 = df1
#df2.loc[df2["col3"] == "male", "gender"] = 1

#print(df2[df2['col3'].str[0].str.isdigit() == 1].index.values)

#print(df[df[‘Name’]==’Donna’].index.values)
#df2.loc[df2["col3"].str[0].str.isdigit() == 1, "col3"] = "Not Rated |"+ df2["col3"]

#df2["col3"] = np.where(df2["col3"].str[0].str.isdigit() == 1, "Not Rated |"+ df2["col3"], df2["col3"])
df1["col3"] = np.where(df1["col3"].str[0].str.isdigit() == 1, "Not Rated |"+ df1["col3"], df1["col3"])

In [9]:
df1['col6'] = df1['col6'].str.replace("Rate ","")

In [10]:
df1['col6'] = df1['col6'].str.replace(" Metascore","")

In [11]:
df1['col6'] = df1['col6'].str.replace("Rate","")


In [12]:
df1.rename(columns={"col5": "Rating", "col6": "Metascore"}, inplace=True)

In [13]:
df1['Metascore'] = df1['Metascore'].str.replace(" ","")
#df1

In [14]:
df1[['Rank', 'TitleAndYear', 'col40', 'col41', 'col42']] = df1['col1'].str.split(".", expand=True)

In [15]:
df1[['Certification', 'Runtime', 'Genre']] = df1['col3'].str.split("|", expand=True)
df1["NoOfGenres"] = df1["Genre"].str.count(',') + 1
#df1 = df1.drop(['col14', 'col15'], axis =1)

In [16]:
df1[['Votes', 'Gross']] = df1['col12'].str.split("|", expand=True)


In [17]:
df1[['Director', 'Stars']] = df1['col10'].str.split("|", expand=True)

In [18]:
df1[['VotesDesc', 'Votes']] = df1['Votes'].str.split(":", expand=True)

In [19]:
df1[['DirectorDesc', 'Director']] = df1['Director'].str.split(":", expand=True)

In [20]:
df1[['StarsDesc', 'Stars']] = df1['Stars'].str.split(":", expand=True)

In [21]:
df1[['GrossDesc', 'Gross']] = df1['Gross'].str.split(":", expand=True)
df1['Gross'] = df1['Gross'].str.replace("$","")
df1['Gross'] = df1['Gross'].str.replace("M","")
df1['Gross'] = df1['Gross'].str.replace(" ","")
df1['Rank'] = df1['Rank'].str.replace(" ","")
#df1['Gross'] = df1['Gross'].astype(int)

<ipython-input-21-4408a0b01c9a>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df1['Gross'] = df1['Gross'].str.replace("$","")


In [22]:
#df2 = df1
df1['Gross'] = df1['Gross'].astype(float)
df1['Votes'] = df1['Votes'].str.replace(" ","")
df1['Votes'] = df1['Votes'].str.replace(",","")
df1['Votes'] = df1['Votes'].astype(int)
df1.rename(columns={"Gross": "Gross$inM"}, inplace=True)

In [23]:
#df1.drop(columns=['col2', 'col4', 'col7', 'col8', 'col9', 'col11'])
df1 = df1.drop(['col2', 'col4', 'col7', 'col8', 'col9', 'col11'], axis =1)


In [24]:
df1 = df1.drop(['col12', 'col13'], axis =1)
df1 = df1.drop(['col3', 'VotesDesc', 'GrossDesc'], axis =1)

In [25]:
#df2 = df1
df1['Year'] = df1["col1"]
df1["Year"] = np.where(df1["Year"].str.find('2014').gt(0), '2014', df1["Year"])
df1["Year"] = np.where(df1["Year"].str.find('2015').gt(0), '2015', df1["Year"])
df1["Year"] = np.where(df1["Year"].str.find('2016').gt(0), '2016', df1["Year"])
df1["Year"] = np.where(df1["Year"].str.find('2017').gt(0), '2017', df1["Year"])
df1["Year"] = np.where(df1["Year"].str.find('2018').gt(0), '2018', df1["Year"])
df1["Year"] = np.where(df1["Year"].str.find('2019').gt(0), '2019', df1["Year"])
df1['Year'] = df1['Year'].astype(int)
df1['Year'].unique()

array([2015, 2016, 2018, 2017, 2019, 2014])

In [26]:
df1['Runtime'] = df1['Runtime'].str.replace(" min","")
df1['Runtime'] = df1['Runtime'].astype(int)
df1.head()

col1 Rating Metascore  \
0     1. The Revenant (I) (2015)     8         76   
1  2. The Invisible Guest (2016)     8              
2           3. Green Book (2018)   8.2         69   
3        4. Hacksaw Ridge (2016)   8.1         71   
4         5. Molly's Game (2017)   7.4         71   

                                               col10          col14  \
0  Director: Alejandro G. Iñárritu | Stars: Leona...   Watch on Max   
1  Director: Oriol Paulo | Stars: Mario Casas, An...           None   
2  Director: Peter Farrelly | Stars: Viggo Morten...           None   
3  Director: Mel Gibson | Stars: Andrew Garfield,...           None   
4  Director: Aaron Sorkin | Stars: Jessica Chasta...           None   

                       col15 Rank                 TitleAndYear col40 col41  \
0  with Prime Video Channels    1      The Revenant (I) (2015)  None  None   
1                       None    2   The Invisible Guest (2016)  None  None   
2                       None    3            Green Book (2018)  None  None   
3                       None    4         Hacksaw Ridge (2016)  None  None   
4                       None    5          Molly's Game (2017)  None  None   

   ... Runtime                       Genre  NoOfGenres   Votes  Gross$inM  \
0  ...     156    Action, Adventure, Drama           3  867466     183.64   
1  ...     106       Crime, Drama, Mystery           3  191184        NaN   
2  ...     130    Biography, Comedy, Drama           3  560737      85.08   
3  ...     139   Biography, Drama, History           3  587526      67.21   
4  ...     140     Biography, Crime, Drama           3  186071      28.78   

                  Director                                              Stars  \
0   Alejandro G. Iñárritu    Leonardo DiCaprio, Tom Hardy, Will Poulter, D...   
1             Oriol Paulo    Mario Casas, Ana Wagener, Jose Coronado, Bárb...   
2          Peter Farrelly    Viggo Mortensen, Mahershala Ali, Linda Cardel...   
3              Mel Gibson    Andrew Garfield, Sam Worthington, Luke Bracey...   
4            Aaron Sorkin    Jessica Chastain, Idris Elba, Kevin Costner, ...   

  DirectorDesc StarsDesc  Year  
0     Director     Stars  2015  
1     Director     Stars  2016  
2     Director     Stars  2018  
3     Director     Stars  2016  
4     Director     Stars  2017  

[5 rows x 22 columns]

In [27]:
#df1['Metascore'] = df1['Metascore'].str.replace(' ','')
df1['Metascore'] = df1['Metascore'].str.strip()
df1['Metascore'] = df1['Metascore'].str.replace(r'\s+', ' ', regex=True)

In [28]:
df1['Metascore'] = df1['Metascore'].fillna('None')

In [29]:
#df2 = df1
#df2["Metascore"] = np.where(df2["Metascore"].str[0].str.isdigit() == 1, df2["Metascore"], "0")
df1["Metascore"] = np.where(df1["Metascore"].str[0].str.isdigit() == 1, df1["Metascore"], "0")

In [30]:
df1['Metascore'] = df1['Metascore'].astype(int)

In [31]:
df1['WatchOnMax'] = df1["col14"]
df1["WatchOnMax"] = np.where(df1["WatchOnMax"].str.find('Watch on Max').gt(0), '1', 0)
df1['WatchOnMax'] = df1['WatchOnMax'].astype(int)
df1['WatchOnMax'].unique()

array([1, 0])

In [32]:
df1['WatchOnPrime'] = df1["col14"]
df1["WatchOnPrime"] = np.where(df1["WatchOnPrime"].str.find('Watch on Prime').gt(0), '1', 0)
df1['WatchOnPrime'] = df1['WatchOnPrime'].astype(int)
df1['WatchOnPrime'].unique()

array([0, 1])

In [33]:
df1['WatchOnNetflix'] = df1["col14"]
df1["WatchOnNetflix"] = np.where(df1["WatchOnNetflix"].str.find('Watch on Netflix').gt(0), '1', 0)
df1['WatchOnNetflix'] = df1['WatchOnNetflix'].astype(int)
df1['WatchOnNetflix'].unique()

array([0, 1])

In [34]:
df1['WatchOnSTARZ'] = df1["col14"]
df1["WatchOnSTARZ"] = np.where(df1["WatchOnSTARZ"].str.find('Watch on STARZ').gt(0), '1', 0)
df1['WatchOnSTARZ'] = df1['WatchOnSTARZ'].astype(int)
df1['WatchOnSTARZ'].unique()

array([0, 1])

In [35]:
df1['WatchOnTBS'] = df1["col14"]
df1["WatchOnTBS"] = np.where(df1["WatchOnTBS"].str.find('Watch on TBS').gt(0), '1', 0)
df1['WatchOnTBS'] = df1['WatchOnTBS'].astype(int)
df1['WatchOnTBS'].unique()

array([0, 1])

In [36]:
df1['WatchOnHulu'] = df1["col14"]
df1["WatchOnHulu"] = np.where(df1["WatchOnHulu"].str.find('Watch on Hulu').gt(0), '1', 0)
df1['WatchOnHulu'] = df1['WatchOnHulu'].astype(int)
df1['WatchOnHulu'].unique()

array([0, 1])

In [37]:
df1['WatchOnParamount'] = df1["col14"]
df1["WatchOnParamount"] = np.where(df1["WatchOnParamount"].str.find('Watch on Paramount').gt(0), '1', 0)
df1['WatchOnParamount'] = df1['WatchOnParamount'].astype(int)
df1['WatchOnParamount'].unique()

array([0, 1])

In [38]:
df1['WatchOnFXNOW'] = df1["col14"]
df1["WatchOnFXNOW"] = np.where(df1["WatchOnFXNOW"].str.find('Watch on FXNOW').gt(0), '1', 0)
df1['WatchOnFXNOW'] = df1['WatchOnFXNOW'].astype(int)
df1['WatchOnFXNOW'].unique()

array([0, 1])

In [39]:
df1 = df1.drop(['col14', 'col15', 'DirectorDesc', 'StarsDesc'], axis =1)

In [40]:
df1 = df1.drop(['col10'], axis =1)

In [41]:
df1['Director'] = df1['Director'].str.strip()
#df1['Director'].unique()
df1['Stars'] = df1['Stars'].str.strip()
#df1['Stars'].unique()

In [42]:
df1['Certification'] = df1['Certification'].str.strip()
#df1['Certification'].unique()

In [43]:
df1['Certification'] = df1['Certification'].str.replace("Not Rated","Unrated")

In [44]:
df1['Action'] = df1["Genre"].str.find('Action')
df1['Adventure'] = df1["Genre"].str.find('Adventure')
df1['Animation'] = df1["Genre"].str.find('Animation')
df1['Biography'] = df1["Genre"].str.find('Biography')
df1['Comedy'] = df1["Genre"].str.find('Comedy')
df1['Crime'] = df1["Genre"].str.find('Crime')
df1['Drama'] = df1["Genre"].str.find('Drama')
df1['Family'] = df1["Genre"].str.find('Family')
df1['Fantasy'] = df1["Genre"].str.find('Fantasy')
df1['History'] = df1["Genre"].str.find('History')
df1['Horror'] = df1["Genre"].str.find('Horror')
df1['Music'] = df1["Genre"].str.find('Music')
df1['Musical'] = df1["Genre"].str.find('Musical')
df1['Mystery'] = df1["Genre"].str.find('Mystery')
df1['Romance'] = df1["Genre"].str.find('Romance')
df1['Sci-Fi'] = df1["Genre"].str.find('Sci-Fi')
df1['Sport'] = df1["Genre"].str.find('Sport')
df1['Thriller'] = df1["Genre"].str.find('Thriller')
df1['War'] = df1["Genre"].str.find('War')
df1['Western'] = df1["Genre"].str.find('Western')


In [45]:
df1['Action'] = df1['Action'].gt(0)
df1['Adventure'] = df1['Adventure'].gt(0)
df1['Animation'] = df1['Animation'].gt(0)
df1['Biography'] = df1['Biography'].gt(0)
df1['Comedy'] = df1['Comedy'].gt(0)
df1['Crime'] = df1['Crime'].gt(0)
df1['Drama'] = df1['Drama'].gt(0)
df1['Family'] = df1['Family'].gt(0)
df1['Fantasy'] = df1['Fantasy'].gt(0)
df1['History'] = df1['History'].gt(0)
df1['Horror'] = df1['Horror'].gt(0)
df1['Music'] = df1['Music'].gt(0)
df1['Musical'] = df1['Musical'].gt(0)
df1['Mystery'] = df1['Mystery'].gt(0)
df1['Romance'] = df1['Romance'].gt(0)
df1['Sci-Fi'] = df1['Sci-Fi'].gt(0)
df1['Sport'] = df1['Sport'].gt(0)
df1['Thriller'] = df1['Thriller'].gt(0)
df1['War'] = df1['War'].gt(0)
df1['Western'] = df1['Western'].gt(0)

df1['Action'] = df1['Action'].replace({
    True:1,
    False:0
})
df1['Adventure'] = df1['Adventure'].replace({
    True:1,
    False:0
})
df1['Animation'] = df1['Animation'].replace({
    True:1,
    False:0
})
df1['Biography'] = df1['Biography'].replace({
    True:1,
    False:0
})
df1['Comedy'] = df1['Comedy'].replace({
    True:1,
    False:0
})
df1['Crime'] = df1['Crime'].replace({
    True:1,
    False:0
})
df1['Drama'] = df1['Drama'].replace({
    True:1,
    False:0
})
df1['Family'] = df1['Family'].replace({
    True:1,
    False:0
})
df1['Fantasy'] = df1['Fantasy'].replace({
    True:1,
    False:0
})
df1['History'] = df1['History'].replace({
    True:1,
    False:0
})
df1['Horror'] = df1['Horror'].replace({
    True:1,
    False:0
})
df1['Music'] = df1['Music'].replace({
    True:1,
    False:0
})
df1['Musical'] = df1['Musical'].replace({
    True:1,
    False:0
})
df1['Mystery'] = df1['Mystery'].replace({
    True:1,
    False:0
})
df1['Romance'] = df1['Romance'].replace({
    True:1,
    False:0
})
df1['Sci-Fi'] = df1['Sci-Fi'].replace({
    True:1,
    False:0
})
df1['Sport'] = df1['Sport'].replace({
    True:1,
    False:0
})
df1['Thriller'] = df1['Thriller'].replace({
    True:1,
    False:0
})
df1['War'] = df1['War'].replace({
    True:1,
    False:0
})
df1['Western'] = df1['Western'].replace({
    True:1,
    False:0
})


In [53]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 400 entries, 0 to 99
Data columns (total 42 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Rating            400 non-null    int64  
 1   Metascore         400 non-null    int64  
 2   Rank              400 non-null    object 
 3   TitleAndYear      400 non-null    object 
 4   col40             8 non-null      object 
 5   col41             3 non-null      object 
 6   col42             1 non-null      object 
 7   Certification     400 non-null    object 
 8   Runtime           400 non-null    int64  
 9   Genre             400 non-null    object 
 10  NoOfGenres        400 non-null    int64  
 11  Votes             400 non-null    int64  
 12  Gross$inM         269 non-null    float64
 13  Year              400 non-null    int64  
 14  WatchOnMax        400 non-null    int64  
 15  WatchOnPrime      400 non-null    int64  
 16  WatchOnNetflix    400 non-null    int64  
 17

In [47]:
df2 = df1

In [48]:
df1['Rating'] = df1['Rating'].str.replace(" ","")
df1['Rating'] = df1['Rating'].astype(float)

In [49]:
df1['Rating'] = df1['Rating'].round().astype(int)

In [50]:
df1['Stars'] = df1['Stars'].fillna('None')

In [52]:
df1 = df1.drop(['Director', 'Stars'], axis =1)
df1 = df1.drop(['col1'], axis =1)
df1 = df1.drop(['Genre'], axis =1)

KeyError: "['Director', 'Stars'] not found in axis"

In [54]:
df1 = df1.drop(['TitleAndYear', 'col40', 'col41', 'col42'], axis =1)

In [55]:
df1["Gross$inM"].fillna(df1["Gross$inM"].mean(), inplace=True)

In [56]:
df1['Rank'] = df1['Rank'].astype('int')

In [71]:
df1 = df1.drop(['Genre'], axis =1)

Rating is influenced by Votes, RunTime, Metascore, Gross$inM, Genres like Drama and Music

Votes are based on these factors (in the same order) - Gross$inM, Metascore, Rating, Sci-Fi, Adventure, Action, Runtime, NoOfGenres, WatchOnHulu, Fantasy, Animation, Music

Rank and Year has positive correlation


---



In [57]:
df1.rename(columns={"Sci-Fi": "SciFi"}, inplace=True)
df1.SciFi.value_counts()


0    379
1     21
Name: SciFi, dtype: int64

In [58]:
df1['Certification'] = df1['Certification'].replace({
    'R': 1,
    'TV-MA': 2,
    'PG-13' : 3,
    'Unrated' : 0,
    'PG': 4,
    'TV-14' : 5,
    'TV-PG' : 6
})

In [72]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 400 entries, 0 to 99
Data columns (total 37 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Rating            400 non-null    int64  
 1   Metascore         400 non-null    int64  
 2   Rank              400 non-null    int64  
 3   Certification     400 non-null    int64  
 4   Runtime           400 non-null    int64  
 5   NoOfGenres        400 non-null    int64  
 6   Votes             400 non-null    int64  
 7   Gross$inM         400 non-null    float64
 8   Year              400 non-null    int64  
 9   WatchOnMax        400 non-null    int64  
 10  WatchOnPrime      400 non-null    int64  
 11  WatchOnNetflix    400 non-null    int64  
 12  WatchOnSTARZ      400 non-null    int64  
 13  WatchOnTBS        400 non-null    int64  
 14  WatchOnHulu       400 non-null    int64  
 15  WatchOnParamount  400 non-null    int64  
 16  WatchOnFXNOW      400 non-null    int64  
 17

In [93]:
y = df1['Rating']
X = df1.drop(['Rating'], axis =1)

Certification to code reference:
    'R': 1,
    'TV-MA': 2,
    'PG-13' : 3,
    'Unrated' : 0,
    'PG': 4,
    'TV-14' : 5,
    'TV-PG' : 6

In [ ]:
#!pip install tensorflow==2.16.0rc0
########### !pip install tensorflow==2.8.0rc1 ## run only this if umap needs to work
#!pip install tensorflow-gpu==2.8.0rc1

In [61]:
import warnings
warnings.filterwarnings("ignore")

import tensorflow as tf

import pandas as pd
import numpy as np

# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#from tensorflow.keras.datasets import mnist

In [74]:
df4 = df1

In [75]:

abalone_features = df4.copy()
abalone_labels = abalone_features.pop('Rating')

abalone_features = np.array(abalone_features)
abalone_features




array([[ 76.,   1.,   1., ...,   0.,   0.,   0.],
       [  0.,   2.,   2., ...,   0.,   0.,   0.],
       [ 69.,   3.,   3., ...,   0.,   0.,   0.],
       ...,
       [ 92., 398.,   1., ...,   1.,   0.,   0.],
       [ 51., 399.,   1., ...,   0.,   0.,   0.],
       [ 40., 400.,   1., ...,   1.,   0.,   0.]])

In [84]:

abalone_model = tf.keras.Sequential([tf.keras.layers.Dense(64),tf.keras.layers.Dense(1)])



In [85]:
abalone_model.compile(loss = tf.keras.losses.MeanSquaredError(),
                      #optimizer = tf.keras.optimizers.Adam())
                      optimizer='sgd')

In [86]:
#np.asarray(X).astype(np.float32)
abalone_model.fit(abalone_features, abalone_labels, epochs=10)

Epoch 1/10
13/13 [==============================] - 0s 2ms/step - loss: nan       
Epoch 2/10
13/13 [==============================] - 0s 2ms/step - loss: nan
Epoch 3/10
13/13 [==============================] - 0s 2ms/step - loss: nan
Epoch 4/10
13/13 [==============================] - 0s 2ms/step - loss: nan
Epoch 5/10
13/13 [==============================] - 0s 2ms/step - loss: nan
Epoch 6/10
13/13 [==============================] - 0s 2ms/step - loss: nan
Epoch 7/10
13/13 [==============================] - 0s 2ms/step - loss: nan
Epoch 8/10
13/13 [==============================] - 0s 2ms/step - loss: nan
Epoch 9/10
13/13 [==============================] - 0s 2ms/step - loss: nan
Epoch 10/10
13/13 [==============================] - 0s 2ms/step - loss: nan


In [87]:
normalize = layers.Normalization()

In [88]:
normalize.adapt(abalone_features)

In [89]:
norm_abalone_model = tf.keras.Sequential([
  normalize,
  layers.Dense(64),
  layers.Dense(1)
])



In [90]:
norm_abalone_model.compile(loss = tf.keras.losses.MeanSquaredError(),
                           #optimizer = tf.keras.optimizers.Adam())
                           optimizer='sgd')



In [91]:
norm_abalone_model.fit(abalone_features, abalone_labels, epochs=10)


Epoch 1/10
13/13 [==============================] - 0s 2ms/step - loss: 27.4209
Epoch 2/10
13/13 [==============================] - 0s 2ms/step - loss: 1.3254
Epoch 3/10
13/13 [==============================] - 0s 2ms/step - loss: 0.3383
Epoch 4/10
13/13 [==============================] - 0s 2ms/step - loss: 0.3094
Epoch 5/10
13/13 [==============================] - 0s 2ms/step - loss: 0.3101
Epoch 6/10
13/13 [==============================] - 0s 2ms/step - loss: 0.3204
Epoch 7/10
13/13 [==============================] - 0s 2ms/step - loss: 0.3127
Epoch 8/10
13/13 [==============================] - 0s 2ms/step - loss: 0.3007
Epoch 9/10
13/13 [==============================] - 0s 2ms/step - loss: 0.3315
Epoch 10/10
13/13 [==============================] - 0s 2ms/step - loss: 0.3322


In [92]:
from sklearn.model_selection import train_test_split

In [94]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [96]:
input_dim = 200  # 28*28
output_dim = nb_classes = 10
batch_size = 25
nb_epoch = 10

'''
X_train = X_train.reshape(400, input_dim)
X_test = X_test.reshape(100, input_dim)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 55
X_test /= 55
'''

"\nX_train = X_train.reshape(400, input_dim)\nX_test = X_test.reshape(100, input_dim)\nX_train = X_train.astype('float32')\nX_test = X_test.astype('float32')\nX_train /= 55\nX_test /= 55\n"

In [97]:
from tensorflow.keras.utils import to_categorical

Y_train = to_categorical(y_train, nb_classes)
Y_test = to_categorical(y_test, nb_classes)

In [102]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation, Dense
from keras import backend as K
from tensorflow.keras import losses

#batch_size = 8

model = Sequential()
# The first dense layer
model.add(Dense(100, input_shape=(36,), activation='relu'))
# The second dense layer
model.add(Dense(50, activation='relu'))
# The last layer is the output layer
model.add(Dense(10, activation='softmax'))

model.summary()

model.compile(optimizer='sgd', loss='categorical_crossentropy',
              metrics=['accuracy'])

# Setting `verbose=1` prints out some results after each epoch
model.fit(X_train, Y_train, batch_size=batch_size, epochs=20, verbose=1)

score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 100)               3700      
                                                                 
 dense_19 (Dense)            (None, 50)                5050      
                                                                 
 dense_20 (Dense)            (None, 10)                510       
                                                                 
Total params: 9260 (36.17 KB)
Trainable params: 9260 (36.17 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
13/13 [==============================] - 1s 2ms/step - loss: 363321179723045797888.0000 - accuracy: 0.4812
Epoch 2/20
13/13 [==============================] - 0s 2ms/step - loss: 2.2616 - accuracy: 0.5625
Epoch 3/20
13/13 [==============================] - 0s 3ms/step - lo

In [104]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation, Dense
from keras import backend as K
from tensorflow.keras import losses

#batch_size = 8

model = Sequential()
# The first dense layer
model.add(Dense(128, input_shape=(36,), activation='tanh'))
# The second dense layer
model.add(Dense(64, activation='tanh'))
# The last layer is the output layer
model.add(Dense(10, activation='softmax'))

model.summary()

model.compile(optimizer='sgd', loss='categorical_crossentropy',
              metrics=['accuracy'])

# Setting `verbose=1` prints out some results after each epoch
model.fit(X_train, Y_train, batch_size=batch_size, epochs=20, verbose=1)

score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_24 (Dense)            (None, 128)               4736      
                                                                 
 dense_25 (Dense)            (None, 64)                8256      
                                                                 
 dense_26 (Dense)            (None, 10)                650       
                                                                 
Total params: 13642 (53.29 KB)
Trainable params: 13642 (53.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
13/13 [==============================] - 0s 2ms/step - loss: 1.5755 - accuracy: 0.5094
Epoch 2/20
13/13 [==============================] - 0s 2ms/step - loss: 1.1530 - accuracy: 0.5656
Epoch 3/20
13/13 [==============================] - 0s 3ms/step - loss: 1.0708 - accu

In [105]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation, Dense
from keras import backend as K
from tensorflow.keras import losses

batch_size = X_train.shape[0]

model = Sequential()
# The first dense layer
model.add(Dense(128, input_shape=(36,), activation='sigmoid'))
# The second dense layer
model.add(Dense(64, activation='sigmoid'))
# The last layer is the output layer
model.add(Dense(10, activation='softmax'))

model.summary()

model.compile(optimizer='sgd', loss='categorical_crossentropy',
              metrics=['accuracy'])

# Setting `verbose=1` prints out some results after each epoch
model.fit(X_train, Y_train, batch_size=batch_size, epochs=20, verbose=1)

score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_27 (Dense)            (None, 128)               4736      
                                                                 
 dense_28 (Dense)            (None, 64)                8256      
                                                                 
 dense_29 (Dense)            (None, 10)                650       
                                                                 
Total params: 13642 (53.29 KB)
Trainable params: 13642 (53.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
1/1 [==============================] - 0s 481ms/step - loss: 2.1493 - accuracy: 0.2125
Epoch 2/20
1/1 [==============================] - 0s 15ms/step - loss: 2.0790 - accuracy: 0.2125
Epoch 3/20
1/1 [==============================] - 0s 13ms/step - loss: 1.9922 - accura

In [106]:
from tensorflow.keras import optimizers
sgd_001 = optimizers.SGD(lr=0.01)
sgd_100 = optimizers.SGD(lr=100)
sgd_00000001 = optimizers.SGD(lr=0.0000001)

In [111]:
# different activation function
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation, Dense
from keras import backend as K
from tensorflow.keras import losses

#batch_size = 128

model = Sequential()
# The first dense layer
model.add(Dense(128, input_shape=(36,), activation='relu'))
# The second dense layer
model.add(Dense(64, activation='relu'))
# The last layer is the output layer
model.add(Dense(10, activation='softmax'))

model.summary()

model.compile(optimizer='sgd', loss='categorical_hinge',
              metrics=['accuracy'])

# Setting `verbose=1` prints out some results after each epoch
model.fit(X_train, Y_train, batch_size=batch_size, epochs=20, verbose=1)

score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_48 (Dense)            (None, 128)               4736      
                                                                 
 dense_49 (Dense)            (None, 64)                8256      
                                                                 
 dense_50 (Dense)            (None, 10)                650       
                                                                 
Total params: 13642 (53.29 KB)
Trainable params: 13642 (53.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
1/1 [==============================] - 1s 512ms/step - loss: 1.6490 - accuracy: 0.1750
Epoch 2/20
1/1 [==============================] - 0s 16ms/step - loss: 1.9990 - accuracy: 0.0000e+00
Epoch 3/20
1/1 [==============================] - 0s 14ms/step - loss: 2.0000 - ac

Test score: 2.0
Test accuracy: 0.0


In [112]:
# different activation function
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation, Dense
from keras import backend as K
from tensorflow.keras import losses

#batch_size = 128

model = Sequential()
# The first dense layer
model.add(Dense(128, input_shape=(36,), activation='tanh'))
# The second dense layer
model.add(Dense(64, activation='tanh'))
# The last layer is the output layer
model.add(Dense(10, activation='softmax'))

model.summary()

model.compile(optimizer='sgd', loss='categorical_hinge',
              metrics=['accuracy'])

# Setting `verbose=1` prints out some results after each epoch
model.fit(X_train, Y_train, batch_size=batch_size, epochs=20, verbose=1)

score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Model: "sequential_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_51 (Dense)            (None, 128)               4736      
                                                                 
 dense_52 (Dense)            (None, 64)                8256      
                                                                 
 dense_53 (Dense)            (None, 10)                650       
                                                                 
Total params: 13642 (53.29 KB)
Trainable params: 13642 (53.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
1/1 [==============================] - 0s 494ms/step - loss: 1.2897 - accuracy: 0.0000e+00
Epoch 2/20
1/1 [==============================] - 0s 14ms/step - loss: 1.1831 - accuracy: 0.0000e+00
Epoch 3/20
1/1 [==============================] - 0s 12ms/step - loss: 1.1538 

Test score: 1.0592339038848877
Test accuracy: 0.03750000149011612


In [113]:
# different activation function
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation, Dense
from keras import backend as K
from tensorflow.keras import losses

#batch_size = 128

model = Sequential()
# The first dense layer
model.add(Dense(128, input_shape=(36,), activation='sigmoid'))
# The second dense layer
model.add(Dense(64, activation='sigmoid'))
# The last layer is the output layer
model.add(Dense(10, activation='softmax'))

model.summary()

model.compile(optimizer='sgd', loss='categorical_hinge',
              metrics=['accuracy'])

# Setting `verbose=1` prints out some results after each epoch
model.fit(X_train, Y_train, batch_size=batch_size, epochs=20, verbose=1)

score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_54 (Dense)            (None, 128)               4736      
                                                                 
 dense_55 (Dense)            (None, 64)                8256      
                                                                 
 dense_56 (Dense)            (None, 10)                650       
                                                                 
Total params: 13642 (53.29 KB)
Trainable params: 13642 (53.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
1/1 [==============================] - 0s 473ms/step - loss: 1.1246 - accuracy: 0.0156
Epoch 2/20
1/1 [==============================] - 0s 13ms/step - loss: 1.1137 - accuracy: 0.0250
Epoch 3/20
1/1 [==============================] - 0s 13ms/step - loss: 1.1039 - accura

In [114]:
# different batch size
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation, Dense
from keras import backend as K
from tensorflow.keras import losses

batch_size = 64

model = Sequential()
# The first dense layer
model.add(Dense(128, input_shape=(36,), activation='relu'))
# The second dense layer
model.add(Dense(64, activation='relu'))
# The last layer is the output layer
model.add(Dense(10, activation='softmax'))

model.summary()

model.compile(optimizer='sgd', loss='categorical_hinge',
              metrics=['accuracy'])

# Setting `verbose=1` prints out some results after each epoch
model.fit(X_train, Y_train, batch_size=batch_size, epochs=20, verbose=1)

score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Model: "sequential_19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_57 (Dense)            (None, 128)               4736      
                                                                 
 dense_58 (Dense)            (None, 64)                8256      
                                                                 
 dense_59 (Dense)            (None, 10)                650       
                                                                 
Total params: 13642 (53.29 KB)
Trainable params: 13642 (53.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
5/5 [==============================] - 1s 7ms/step - loss: 1.9991 - accuracy: 0.0000e+00
Epoch 2/20
5/5 [==============================] - 0s 6ms/step - loss: 2.0000 - accuracy: 0.0000e+00
Epoch 3/20
5/5 [==============================] - 0s 3ms/step - loss: 2.0000 - ac

In [115]:
# different batch size
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation, Dense
from keras import backend as K
from tensorflow.keras import losses

batch_size = 128

model = Sequential()
# The first dense layer
model.add(Dense(128, input_shape=(36,), activation='relu'))
# The second dense layer
model.add(Dense(64, activation='relu'))
# The last layer is the output layer
model.add(Dense(10, activation='softmax'))

model.summary()

model.compile(optimizer='sgd', loss='categorical_hinge',
              metrics=['accuracy'])

# Setting `verbose=1` prints out some results after each epoch
model.fit(X_train, Y_train, batch_size=batch_size, epochs=20, verbose=1)

score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Model: "sequential_20"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_60 (Dense)            (None, 128)               4736      
                                                                 
 dense_61 (Dense)            (None, 64)                8256      
                                                                 
 dense_62 (Dense)            (None, 10)                650       
                                                                 
Total params: 13642 (53.29 KB)
Trainable params: 13642 (53.29 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
3/3 [==============================] - 1s 7ms/step - loss: 0.8750 - accuracy: 0.5625
Epoch 2/20
3/3 [==============================] - 0s 6ms/step - loss: 0.8750 - accuracy: 0.5625
Epoch 3/20
3/3 [==============================] - 0s 7ms/step - loss: 0.8750 - accuracy: 